# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176eb2f837a5e0a9429cd2bc165a56f371bfe0260c676ef4b10e7844d94db2e9146b7cc9104f202b19a68dfd7e513fdc75dc229fdeae74911ee9c792fec899fc

test:
  secret_key_base: 51d92fc6c095c854f27b3bad7f118010533e71437d0cf7912eae34c5c0cc5177ad3d6fafc8ceecfabe4a1c0311b61458e89e4a9ee837c8c16a768b931bf566d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
